### ISSUE TITLE
https://unpkg.com/shp-write@latest/shpwrite.js not updated to v0.4.0

### ISSUE THREAD

**Issue by GabrielMrqs** [mapbox/shp-write#101]
Please update to v0.4.0 in unpkg too

**Comment by sheindel** [comment]
Unfortunately, Mapbox changed their deployment organization so this library is now hosted under a different package name

You can find the new unpkg link here

https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js

**Comment by GabrielMrqs** [comment]
thats nice, thank you 😄
