### ISSUE TITLE
TextEncoder (new)

### ISSUE THREAD

**Issue by sainsb** [mapbox/shp-write#19]
Using the browser version :
Chrome:
`Uncaught TypeError: Failed to construct 'TextEncoder': Please use the 'new' operator, this DOM object constructor cannot be called as a function.`

Firefox:
`TypeError: Constructor TextEncoder requires 'new'`

**Comment by btfou** [comment]
Yep. Adding `new` to TextEncoder here:
https://github.com/mapbox/shp-write/blob/master/shpwrite.js#L3922
and here:
https://github.com/mapbox/shp-write/blob/master/shpwrite.js#L4694
and it works.

**Comment by tmcw** [comment]
Those are built files - this problem looks like it's upstream in jszip

**Comment by tmcw** [comment]
upstream: https://github.com/Stuk/jszip/issues/179
