### ISSUE TITLE
Poly Write

### ISSUE THREAD

**Issue by sainsb** [mapbox/shp-write#21]
Rather than issue a pull request, I'm logging this as an issue. with a solution.

https://github.com/mapbox/shp-write/blob/master/src/poly.js#L43
`shpI += contentLength;`

should be:

`shpI += contentLength +8;`

Note that this affects GeoJSON.io as well.  Multiple polygons to shapefile == fail until this fix is implemented.

Oh Yeah, this one too:
https://github.com/mapbox/shp-write/blob/master/src/poly.js#L25

`shxOffset += contentLength;`

should be:

`shxOffset += contentLength+8;`

many Bothans died ....

**Comment by jfgodoy** [comment]
same issue here. I applied the changes that @sainsb said and works well.

**Comment by tmcw** [comment]
Fixed in #23
