### ISSUE TITLE
Need to update dbf dependency

### ISSUE THREAD

**Issue by mbloch** [mapbox/shp-write#29]
shp-write currently depends on v0.1.0 of dbf, which has a few serious bugs. It causes the 0x0D header terminator to be written to the wrong location, and it overwrites the last data byte of the last data record with 0x1A (EOF). Updating to the current version of dbf (0.1.2) will fix. (This bug currently affects all Shapefiles generated by geojson.io).

**Comment by tmcw** [comment]
Thanks for the heads-up! I've released 0.2.5. with updated dependencies.
