### ISSUE TITLE
Support donut (hole) polygon

### ISSUE THREAD

**Issue by jvail** [mapbox/shp-write#30]
I needed Polys with holes and therefore put some code together ... quite annoying to deal with all those arrays of arrays of ...

I tested it with a few odd combinations of (Multi-)polys with and without holes. You might want to take a look at it - and finally pull it if you think it makes sense ...  https://github.com/jvail/shp-write

Jan

P.S.: ... thank you for this project (with or without holes)

**Comment by chriswhong** [comment]
+1 for this, I was attempting to use this library to download isochrones created by OpenTripPlanner.  OTP outputs a FeatureCollection, each feature being a MultiPolygon that can have lots of holes.
![travelsheds](https://cloud.githubusercontent.com/assets/1833820/18394247/f5b485c2-7686-11e6-8b93-5ded5ca5408c.png)

It downloads a zip with an empty folder and not much feedback about what went wrong.  I also tried using the fork that @jvail wrote, but the same thing (empty zipped folder) happened.

**Comment by jvail** [comment]
Could you post a link to the data set (or a part of it)?

**Comment by tmcw** [comment]
Merged with #36

**Comment by landonreed** [comment]
There appears to still be `MultiPolygon` features that `shp-write` cannot write.  For example: http://bl.ocks.org/d/00101a5db22d0f4e914993bc0a2e2a1f

**Comment by jvail** [comment]
Sorry, I'd like to but after all those years I am unable to recover my original problem. Thanks for fixing :)
