### ISSUE TITLE
Different encoding

### ISSUE THREAD

**Issue by Trokul** [mapbox/shp-write#33]
Hey, the features I'd like to export, have attributes in Hebrew, and the writer turn then to Gibberish. I like to know if there is a way I could change the dbf file encoding, or an other way to export in Hebrew.

Thanks!

**Comment by tmcw** [comment]
Unfortunately that'll have to be out of scope for this module - the DBF standard, being a very old thing, [uses an old encoding that isn't utf8](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). Only a compatible subset of that encoding and UTF8 (so, essentially, just ASCII) should be expected to work reliably.
