### ISSUE TITLE
Attribute data rounded to nearest integer

### ISSUE THREAD

**Issue by jcoombs20** [mapbox/shp-write#38]
Values for attributes are rounded to the nearest integer for shapefile zip outputs which renders data such as probabilities meaningless. It would be great if this, and the parts problem with point data mentioned in the previous issue could be resolved. Otherwise, thanks for the package.

**Comment by jvail** [comment]
@jcoombs20 : that needs to be fixed in the dbf repo https://github.com/mapbox/dbf/. 
If you need a quick&dirty solution - as I do - just replace the 0 with e.g. 3 (no. decimals) here https://github.com/mapbox/dbf/blob/master/src/structure.js#L55.

**Comment by jcoombs20** [comment]
Thanks jvail, that worked perfectly!

**Comment by tmcw** [comment]
Fixed in d5032aca48cd89e739f47b0b490cbe4657eadda5
