### ISSUE TITLE
Error: This method has been removed in JSZip 3.0, please check the upgrade guide.

### ISSUE THREAD

**Issue by ghost** [mapbox/shp-write#48]
Hi,
I'm using the latest version 0.3.2 and when executing shpwrite.download() I get following Error:

`Error: This method has been removed in JSZip 3.0, please check the upgrade guide.`

Do I do something wrong or is it a bug? Is there a work-around?

Here is my code;:
           
var shp_options = {
  folder: 'shapefiles',
  types: {
     point: 'points',
     polygon: 'polygons',
     polyline: 'polyline'
  }};
var geojson_format = new OpenLayers.Format.GeoJSON();
var features_geojson = JSON.parse(geojson_format.write(drawLayer.features,false));  
shpwrite.download(features_geojson,shp_options);

Cheers,
Steffen

**Comment by malvandi** [comment]
Do you have solved it?
I have the same problem.

**Comment by sjohn-atenekom** [comment]
no, unfortunately not. I still don't have the shape write implement. Until now I can live with geojson...

**Comment by simtrax** [comment]
I have this issue as well.

**Comment by ximex** [comment]
I fixed it by hand.
Replace this:
```js
// replace this:
return zip.generate(generateOptions);
// with this:
return zip.generateAsync(generateOptions).then(function(content) {
  // use content
});
```
Look at: https://stuk.github.io/jszip/documentation/upgrade_guide.html

**Comment by kmanzana** [comment]
Does it make sense to introduce this change via a PR?
