### ISSUE TITLE
Download method generates a zip file without extension

### ISSUE THREAD

**Issue by rijatru** [mapbox/shp-write#57]
Calling shpWrite.download(geoJson, options) downloads a file named download without the zip extension.

**Comment by sheindel** [comment]
Good news: v0.4.2 is now available and this issue should be resolved.

Less good news: Mapbox changed their deployment organization so this package is now hosted under a different package

@mapbox/shp-write
https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js
