### ISSUE TITLE
Request: Support Multipoint Geometry

### ISSUE THREAD

**Issue by jeff-tenhave** [mapbox/shp-write#59]
It would be awesome if shp-write would support writing geometry with type 'Multipoint'. Currently these geometries are ignored and not written to the shapefile.

**Comment by jeff-tenhave** [comment]
I've added [PR](https://github.com/mapbox/shp-write/pull/60) for this.

**Comment by sheindel** [comment]
Good news: v0.4.2 is now available, and should resolve this issue.

Less good news: Mapbox changed their deployment organization so this package is now hosted under a different package

@mapbox/shp-write
https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js
