### ISSUE TITLE
Does it support polygon with multiple rings or holes?

### ISSUE THREAD

**Issue by mickeyjohn** [mapbox/shp-write#63]
Hi, 
Does the library support polygons with multiple rings or holes yet? I can not find one within the examples or documentation. 

Thanks a lot.

**Comment by rajkishan16** [comment]
Did you find a way to do this? Right now, when I try to convert a Geojson with a hole into a shapefile using shp-write, I'm only getting two separate polygons.

**Comment by rajkishan16** [comment]
Never mind. Looks like it is indeed exporting properly. It's while reading the shapefile that it's showing multiple polygons. I can take care of that on my end.
