### ISSUE TITLE
Add option to zip files without folder

### ISSUE THREAD

**Issue by dulldrums** [mapbox/shp-write#70]
#### Problem
When zipping and downloading a shp file, jsZip creates a folder to put the files in. When the downloaded zip file is loaded into QGIS, it throws an error because it has a folder inside it.

#### Workaround
Unzip the downloaded zip file, and drag the resulting folder into QGIS.

#### Notes
Not really a critical issue, more of a convenience thing.

**Comment by dulldrums** [comment]
I have a fix for this issue, ill submit a PR tomorrow

**Comment by baxter1707** [comment]
@dulldrums Do you know if this is going to be merged into master? This would be very useful.

**Comment by sheindel** [comment]
This has been fixed in the latest tag (v0.4.0). Will be released on npm soon.

**Comment by sheindel** [comment]
Good news: v0.4.2 is now available.

Less good news: Mapbox changed their deployment organization so this package is now hosted under a different package

[@mapbox/shp-write](https://www.npmjs.com/package/@mapbox/shp-write)
https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js
