### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by TBusan** [mapbox/shp-write#85]
when i export to shp ,Chinese garbled

**Comment by WangMingHua111** [comment]
[dbf issues #21](https://github.com/mapbox/dbf/issues/21)
的确可以解决shp写入后中文乱码的问题

**Comment by TerrainHome** [comment]
怎么解决呢？

**Comment by sheindel** [comment]
This is really an underlying `dbf` issue, feel free to open this issue there
