### ISSUE TITLE
The result of zip(geojson) isn't ArrayBuffer but Base64 by deafult.

### ISSUE THREAD

**Issue by YuWebGIS** [mapbox/shp-write#86]

**Comment by neon-ninja** [comment]
Here's how you can convert it: `Uint8Array.from(atob(base64_string), c => c.charCodeAt(0))`

**Comment by YuWebGIS** [comment]
> Here's how you can convert it: `Uint8Array.from(atob(base64_string), c => c.charCodeAt(0))`

Thank you! I will try it.
