### ISSUE TITLE
I have 4 features in my collection, when downloaded file it puts coordinates of all 4 features into 1. I need all 4 features not 1, can anyone help?

### ISSUE THREAD

**Issue by RambhauWaykar** [mapbox/shp-write#88]

**Comment by ogiovanniruiz** [comment]
I have the same issue.

**Comment by klmc66666** [comment]
my geojson  has  3 polygoon  not  mutipolygon，when  i  download ，it's change to  1 mutipolygon  and  dbf  is has 3 record

**Comment by aafenlared** [comment]
Hello everyone.  This one have the same problem:  https://unpkg.com/shp-write@latest/shpwrite.js

**Comment by HugoP27** [comment]
I have the same problem, any solutions yet?
