### ISSUE TITLE
jszip dependency security vulnerability

### ISSUE THREAD

**Issue by rooby** [mapbox/shp-write#92]
The jszip dependency version has a vulnerability and should be updated.
See https://github.com/advisories/GHSA-jg8v-48h5-wgxg

**Comment by sheindel** [comment]
Resolved as of tag v0.4.0, should be on npm soon.

**Comment by sheindel** [comment]
Good news: v0.4.2 is now available.

Less good news: Mapbox changed their deployment organization so this package is now hosted under a different package

[@mapbox/shp-write](https://www.npmjs.com/package/@mapbox/shp-write)
https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js

**Comment by rooby** [comment]
Thanks for your efforts on getting this new version out @sheindel 
Aside from the PR I opened about the types it seems to be working for my usage.
