### ISSUE TITLE
Convert Source Code to TypeScript

### ISSUE THREAD

**Issue by charlieforward9** [mapbox/shp-write#94]

**Comment by sheindel** [comment]
There are a lot of reasons that it's actually much easier to maintain a simple library like this if it's just pure `js` with a `types` definition vs full TypeScript. I'm a huge TypeScript fan and proponent, but given the age of this library, I think js + types is a better option.

Thanks so much for helping contribute to the type definitions!

**Comment by sheindel** [comment]
Good news: v0.4.2 is now available.

Less good news: Mapbox changed their deployment organization so this package is now hosted under a different package

[@mapbox/shp-write](https://www.npmjs.com/package/@mapbox/shp-write)
https://unpkg.com/@mapbox/shp-write@latest/shpwrite.js
